<?php

namespace Omg;

use Bitrix\Main\Entity;

class BookTable extends Entity\DataManager{

    public static function getTableName()
    {
        return 'ng_books';
    }

    public static function getUfId()
    {
        return 'NG_BOOKS';
    }

    public static function getObjectClass()
    {
        return parent::getObjectClass(); // TODO: Change the autogenerated stub
    }

    public static function getMap()
    {
        return array(
            new Entity\IntegerField('ID', array(
                'primary' => true,
                'autocomplete' => true
            )),
            new Entity\StringField('UF_AUTHOR', array(
                'required' => true,
            )),
            new Entity\StringField('UF_BOOK_NAME'),
            new Entity\IntegerField('UF_CATALOG_ID')
        );
    }


}